"use strict";
let currentLang = localStorage.getItem("doshaLanguage") || "vi";
let currentView = "quiz";
let currentSection = Number(localStorage.getItem("doshaSection") || 0);
let started = localStorage.getItem("doshaStarted") === "true";
let isSharedView = false;
let selections = {name:"", prakruti:{}, vikruti:{}};
const sectionIds = ["physical","functional","psychological"];
const doshas = ["vata","pitta","kapha"];
const t = {
 en:{header:"Ayurvedic Dosha Quiz",introTitle:"Discover Your Ayurvedic Constitution",introCopy:"A quiet moment of observation to understand your natural constitution and what may be changing now.",prakrutiCopy:"Your natural constitution and the relatively stable tendencies you have experienced throughout life.",vikrutiCopy:"Changes or imbalances that are showing themselves at the present time.",meta:"31 questions · approximately 8–10 minutes",start:"Start the Quiz",sections:["A. Physical","B. Body functions","C. Psychological"],sectionNames:["Physical Characteristics","Physical Functional Characteristics","Psychological Characteristics"],part:"Section",questions:"questions",long:"Long-term tendency",current:"Current imbalance",optional:"optional — tap again to clear",previous:"Previous",continue:"Continue",results:"View results",unanswered:n=>`You still have ${n} unanswered long-term tendency question${n===1?'':'s'}.`,jump:"Go to first unanswered",resultsTitle:"Your Ayurvedic profile",natural:"Natural constitution — Prakruti",imbalance:"Current imbalance — Vikruti",rank:"Rank",primary:"Primary",secondary:"Secondary",tertiary:"Tertiary",copy:"Copy link",share:"Share",print:"Print",reset:"Retake quiz",understand:"Understanding the doshas",viewQuiz:"Dosha Quiz",viewForm:"Intake Form",shared:"You are viewing a shared Dosha profile.",notDiagnosis:"This educational reflection is not a medical diagnosis.",vataInfo:"Air & Space · movement, creativity and vitality.",pittaInfo:"Fire & Water · transformation, intelligence and courage.",kaphaInfo:"Earth & Water · structure, calmness and compassion."},
 vi:{header:"Bài trắc nghiệm Ayurveda",introTitle:"Khám phá thể trạng Ayurveda của bạn",introCopy:"Một khoảng lặng để quan sát thể trạng tự nhiên của bạn và những gì có thể đang thay đổi ở hiện tại.",prakrutiCopy:"Thể trạng tự nhiên và những khuynh hướng tương đối ổn định của bạn từ trước đến nay.",vikrutiCopy:"Những thay đổi hoặc mất cân bằng đang biểu hiện ở thời điểm hiện tại.",meta:"Bài trắc nghiệm gồm 31 câu · khoảng 8–10 phút",start:"Bắt đầu bài trắc nghiệm",sections:["A. Thể chất","B. Chức năng cơ thể","C. Tâm lý"],sectionNames:["Đặc điểm thể chất","Đặc điểm chức năng cơ thể","Đặc điểm tâm lý"],part:"Phần",questions:"câu",long:"Khuynh hướng lâu dài",current:"Mất cân bằng hiện tại",optional:"không bắt buộc · chạm lại để bỏ chọn",previous:"Quay lại",continue:"Tiếp tục",results:"Xem kết quả",unanswered:n=>`Bạn còn ${n} câu chưa chọn ở phần Khuynh hướng lâu dài.`,jump:"Đến câu đầu tiên",resultsTitle:"Hồ sơ thể trạng Ayurveda",natural:"Thể trạng tự nhiên — Prakruti",imbalance:"Mất cân bằng hiện tại — Vikruti",rank:"Xếp hạng",primary:"Chính",secondary:"Phụ",tertiary:"Thứ ba",copy:"Sao chép link",share:"Chia sẻ",print:"In hồ sơ",reset:"Làm lại",understand:"Tìm hiểu về các Dosha",viewQuiz:"Bài trắc nghiệm",viewForm:"Hồ sơ y tế",shared:"Bạn đang xem một hồ sơ thể trạng được chia sẻ.",notDiagnosis:"Nội dung mang tính giáo dục, không phải chẩn đoán y khoa.",vataInfo:"Khí & Không gian · chuyển động, sáng tạo và sức sống.",pittaInfo:"Lửa & Nước · chuyển hóa, trí tuệ và can đảm.",kaphaInfo:"Đất & Nước · cấu trúc, bình tĩnh và lòng từ bi."}
};
function esc(value){const d=document.createElement("div");d.textContent=value;return d.innerHTML}
function loadLocalData(){try{const saved=JSON.parse(localStorage.getItem("doshaSelections"));if(saved) selections={name:saved.name||"",prakruti:saved.prakruti||{},vikruti:saved.vikruti||{}}}catch(e){console.warn("Stored quiz state could not be read",e)}}
function saveLocalData(){localStorage.setItem("doshaSelections",JSON.stringify(selections));localStorage.setItem("doshaLanguage",currentLang);localStorage.setItem("doshaSection",String(currentSection))}
function setLang(lang){const showingResults=Boolean(document.getElementById("results").innerHTML);currentLang=lang;document.documentElement.lang=lang;localStorage.setItem("doshaLanguage",lang);renderChrome();if(showingResults)displayDashboard(getCurrentCounts(),isSharedView);else if(started)renderQuiz()}
function renderChrome(){const x=t[currentLang];document.getElementById("header-title").textContent=x.header;document.getElementById("intro-title").textContent=x.introTitle;document.getElementById("intro-copy").textContent=x.introCopy;document.getElementById("prakruti-copy").textContent=x.prakrutiCopy;document.getElementById("vikruti-copy").textContent=x.vikrutiCopy;document.getElementById("quiz-meta").textContent=x.meta;document.getElementById("start-btn").textContent=x.start;document.getElementById("btn-view-quiz").textContent=x.viewQuiz;document.getElementById("btn-view-form").textContent=x.viewForm;["vi","en"].forEach(l=>document.getElementById(`btn-${l}`).classList.toggle("active",l===currentLang))}
function startQuiz(){started=true;localStorage.setItem("doshaStarted","true");document.getElementById("intro").hidden=true;document.getElementById("questionnaire").hidden=false;renderQuiz();window.scrollTo({top:70,behavior:"smooth"})}
function switchView(view){currentView=view;document.getElementById("quiz-view").style.display=view==="quiz"?"block":"none";document.getElementById("form-view").style.display=view==="form"?"block":"none";document.getElementById("btn-view-quiz").classList.toggle("active",view==="quiz");document.getElementById("btn-view-form").classList.toggle("active",view==="form");if(view==="form"&&!document.getElementById("history-grid").children.length)renderHistory()}
function renderHistory(){document.getElementById("history-grid").innerHTML=historyOptions.map((o,i)=>`<div class="history-item"><span>${esc(o)}</span><div class="history-checks"><label><input type="checkbox" name="history-me-${i}"> Me</label><label><input type="checkbox" name="history-family-${i}"> Fam</label></div></div>`).join("")}
function renderQuiz(){const x=t[currentLang], section=sectionIds[currentSection], subset=questions.filter(q=>q.section===section);document.getElementById("intro").hidden=true;document.getElementById("questionnaire").hidden=false;document.getElementById("results").innerHTML="";document.getElementById("long-label").textContent=x.long;document.getElementById("current-label").textContent=x.current;document.getElementById("optional-label").textContent=x.optional;document.getElementById("section-tabs").innerHTML=x.sections.map((label,i)=>`<button type="button" class="${i===currentSection?'active':''}" ${i>currentSection&&!sectionComplete(i-1)?'disabled':''} onclick="goSection(${i})">${label}</button>`).join("");const answered=subset.filter(q=>selections.prakruti[q.id]).length;document.getElementById("section-meta").textContent=`${x.part} ${String.fromCharCode(65+currentSection)} / 3 · ${x.sectionNames[currentSection]}`;document.getElementById("answer-meta").textContent=`${answered} / ${subset.length} ${x.questions}`;const total=Object.keys(selections.prakruti).filter(id=>questions.some(q=>q.id===id)).length;document.getElementById("progress-bar").style.width=`${total/31*100}%`;document.querySelector(".progress-track").setAttribute("aria-valuenow",total);document.getElementById("quiz-content").innerHTML=subset.map((q,i)=>questionHTML(q,i)).join("");document.getElementById("previous-btn").textContent=x.previous;document.getElementById("previous-btn").style.visibility=currentSection===0?"hidden":"visible";document.getElementById("continue-btn").textContent=currentSection===2?x.results:x.continue;document.getElementById("validation").hidden=true}
function questionHTML(q,i){const d=q[currentLang];return `<article class="question-block" id="question-${q.id}"><div class="question-heading"><span class="question-number">${String(i+1).padStart(2,'0')}</span><h2>${esc(d.trait)}</h2></div><div class="options">${doshas.map((dosha,index)=>`<div class="option-row"><label class="description"><input class="prakruti-control" type="radio" name="prakruti-${q.id}" ${selections.prakruti[q.id]===dosha?'checked':''} onchange="selectOption('prakruti','${q.id}','${dosha}')" aria-label="${esc(t[currentLang].long+': '+d[dosha])}"><i class="fake-radio" aria-hidden="true"></i><span>${esc(d[dosha])}</span></label><label class="current-control"><input type="checkbox" ${selections.vikruti[q.id]===dosha?'checked':''} onchange="selectOption('vikruti','${q.id}','${dosha}')" aria-label="${esc(t[currentLang].current+': '+d[dosha])}"><span>${esc(t[currentLang].current)}</span></label></div>`).join("")}</div></article>`}
function selectOption(type,id,dosha){if(type==="vikruti"&&selections.vikruti[id]===dosha)delete selections.vikruti[id];else selections[type][id]=dosha;isSharedView=false;saveLocalData();renderQuiz();document.getElementById(`question-${id}`).scrollIntoView({block:"center"})}
function sectionComplete(i){return questions.filter(q=>q.section===sectionIds[i]).every(q=>selections.prakruti[q.id])}
function goSection(i){if(i<=currentSection||sectionComplete(currentSection)){currentSection=i;saveLocalData();renderQuiz();window.scrollTo({top:75,behavior:"smooth"})}}
function previousSection(){if(currentSection){currentSection--;saveLocalData();renderQuiz();window.scrollTo({top:75,behavior:"smooth"})}}
function continueSection(){const missing=questions.filter(q=>q.section===sectionIds[currentSection]&&!selections.prakruti[q.id]);if(missing.length){const box=document.getElementById("validation");box.innerHTML=`${esc(t[currentLang].unanswered(missing.length))}<button onclick="document.getElementById('question-${missing[0].id}').scrollIntoView({behavior:'smooth'})">${esc(t[currentLang].jump)}</button>`;box.hidden=false;return}if(currentSection<2){currentSection++;saveLocalData();renderQuiz();window.scrollTo({top:75,behavior:"smooth"})}else calculateResults()}
function getCurrentCounts(){const c={prakruti:{vata:0,pitta:0,kapha:0},vikruti:{vata:0,pitta:0,kapha:0}};["prakruti","vikruti"].forEach(type=>Object.values(selections[type]).forEach(d=>{if(doshas.includes(d))c[type][d]++}));return c}
function calculateResults(){const missing=questions.filter(q=>!selections.prakruti[q.id]);if(missing.length){currentSection=sectionIds.indexOf(missing[0].section);renderQuiz();continueSection();return}document.getElementById("questionnaire").hidden=true;displayDashboard(getCurrentCounts(),false);window.scrollTo({top:75,behavior:"smooth"})}
function ranks(scores){return [...doshas].sort((a,b)=>scores[b]-scores[a]||doshas.indexOf(a)-doshas.indexOf(b))}
function displayDashboard(counts,isShared){const x=t[currentLang];const result=(type,title)=>{const rank=ranks(counts[type]),max=Math.max(1,...Object.values(counts[type]));return `<section class="result-box"><h2>${title}</h2>${doshas.map(d=>`<div class="score-row ${d}"><span>${d[0].toUpperCase()+d.slice(1)}</span><span class="score-track"><i style="width:${counts[type][d]/max*100}%"></i></span><b>${counts[type][d]}</b></div>`).join("")}<table class="ranking"><thead><tr><th>${x.rank}</th><th>Dosha</th></tr></thead><tbody>${rank.map((d,i)=>`<tr><td>${[x.primary,x.secondary,x.tertiary][i]}</td><td>${d[0].toUpperCase()+d.slice(1)}</td></tr>`).join("")}</tbody></table></section>`};document.getElementById("results").innerHTML=`<div class="results-shell"><header class="results-head"><p class="eyebrow">Twin Beans Farm · Ayurveda</p><h1>${x.resultsTitle}</h1><p>${x.notDiagnosis}</p></header><div class="results-grid">${result("prakruti",x.natural)}${result("vikruti",x.imbalance)}</div><div class="action-buttons">${isShared?'':`<button class="action-btn" onclick="exportToText()">${x.copy}</button><button class="action-btn" onclick="shareResults()">${x.share}</button>`}<button class="action-btn" onclick="window.print()">${x.print}</button><button class="action-btn" onclick="resetQuizData()">${x.reset}</button></div><div class="dosha-info-grid">${doshas.map(d=>`<article class="dosha-info-card"><h3>${d[0].toUpperCase()+d.slice(1)}</h3><p>${x[d+'Info']}</p></article>`).join("")}</div></div>`}
async function saveShared(){const response=await fetch("/.netlify/functions/saveQuiz",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(selections)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const result=await response.json();return `${location.origin}${location.pathname}?id=${encodeURIComponent(result.id)}&l=${currentLang}`}
async function exportToText(){try{await navigator.clipboard.writeText(await saveShared())}catch(e){console.error("Unable to copy shared profile",e)}}
async function shareResults(){try{const url=await saveShared();if(navigator.share)await navigator.share({title:t[currentLang].resultsTitle,url});else await navigator.clipboard.writeText(url)}catch(e){console.error("Unable to share profile",e)}}
function resetQuizData(){selections={name:"",prakruti:{},vikruti:{}};currentSection=0;started=false;isSharedView=false;localStorage.removeItem("doshaSelections");localStorage.removeItem("doshaStarted");localStorage.removeItem("doshaSection");history.replaceState({},document.title,location.pathname);document.getElementById("results").innerHTML="";document.getElementById("questionnaire").hidden=true;document.getElementById("intro").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
async function init(){renderChrome();const params=new URLSearchParams(location.search);if(params.get("l")&&t[params.get("l")])currentLang=params.get("l");if(params.has("id")){try{const response=await fetch(`/.netlify/functions/getQuiz?id=${encodeURIComponent(params.get("id"))}`);if(response.ok){selections=await response.json();isSharedView=true;started=true;document.getElementById("questionnaire").hidden=true;document.getElementById("intro").hidden=true;const b=document.getElementById("shared-banner");b.textContent=t[currentLang].shared;b.hidden=false;renderChrome();displayDashboard(getCurrentCounts(),true);return}}catch(e){console.error("Unable to load shared quiz",e)}}loadLocalData();renderChrome();if(started)startQuiz()}
init();
